line-length = 99
indent-width = 4
target-version = "py39"

[lint]
select = ["ALL"]
ignore = ["E501", "COM812", "EXE003"]
fixable = ["ALL"]
unfixable = []

[lint.pydocstyle]
convention = "google"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint.per-file-ignores]
"/*tests/*.py" = [
    # at least this three should be fine in tests:
    "D100",
    "INP001",
    "ANN201",
    "S101",   # asserts allowed in tests...
    "ARG",    # Unused function args -> fixtures nevertheless are functionally relevant...
    "FBT",    # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
    # The below are debatable
    "PLR2004", # Magic value used in comparison, ...
    "S311",    # Standard pseudo-random generators are not suitable for cryptographic purposes
]
"example/*" = ["D100", "INP001"]
"scripts/*" = ["D100", "INP001"]
